name: ssh-pull-deploy

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        env:
          app: "deepstream-mri"
          username: "yangyanting"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: app,username
          script: |
            docker pull ${username}/${app}
            docker stop ${app}
            docker rm ${app}
            docker run --init -d -p 5000:5000 --name=${app} ${username}/${app}
            docker system prune -af
